# 服务端口号
server:
    port: 10001
    
# 服务名称
spring:
    application:
        name: bgs-config-server
    profiles:
        active: native  
    cloud:
        config:
            server:
                bootstrap: true
                native:
#                    searchLocations: file:D:\\dev\\github\\BGS\\bgs-server\\base\\config-server\\src\\main\\config
                    searchLocations: classpath:bgs-config/
        

  
#Eureka 相关配置
eureka:
    client:
        service-url:
            defaultZone: http://localhost:10000/eureka/
#            defaultZone: http://172.17.0.2:10000/eureka/
#        # 是否从其他的服务中心同步服务列表
#        fetch-registry: false
        # 是否把自己作为服务注册到其他服务注册中心
        register-with-eureka: true
