# 服务名称
spring:
    application:
        name: bgs-admin-server
    cloud:
        # 统一配置服务
        config:
            uri: http://localhost:10001/
            profile: local
            label: master
            discovery:
                enable: true
                service-id: config-server
    boot:
        admin:
            ui:
                title: MYC-BGS Admin
                brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>MYC-BGS Admin</span>
# 服务端口号
server:
    port: 13000

#Eureka 相关配置
eureka:
    client:
        service-url:
            defaultZone: http://localhost:10000/eureka/
#        # 是否从其他的服务中心同步服务列表
#        fetch-registry: false
        # 是否把自己作为服务注册到其他服务注册中心
        register-with-eureka: true
    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                incloud: refresh,health,info,env,loggers,metrics,trace,dump
        health:
            show-details: always
